### ISSUE TITLE
Template project for C++

### ISSUE THREAD

**Issue by sharpgeek** [IARSystems/iar-risc-v-gd32v-eval#12]
Hi @felipe-iar 

I am planning to start working on a C++ project using the EWRISCV and the eval board. 
Would be possible to clarify the prerequisites in order to create a C++ project under this scenario?

Perhaps a C++ project example or template could be helpful.

Many thanks.

**Comment by felipe-iar** [comment]
Hi @sharpgeek,

It is a nice idea.

Even then, right now we do not have any plans of publishing a template for C++ projects from our side. Still, even if the [__GD32VF103 Firmware Library__](https://github.com/GigaDevice-Semiconductor/GD32VF103_Firmware_Library/) from GigaDevice was written in C, it comes prepared to play nicely along C++ projects because its implementation uses `extern "C"` to cope with the name mangling and allow such a mix.

```cpp
#ifdef __cplusplus
  extern "C" {
#endif 

// <some C code goes here>

#ifdef __cplusplus
  }
#endif
```

The `__cplusplus` symbol is generated automatically by the IAR C/C++ compiler when building C++ modules.

Anyway, if you have done some work related to that or have created any cool project with the evaluation board, please feel free to create a new project and then perform a pull request for the __contributions__ folder.

**Comment by sharpgeek** [comment]
Hi @felipe-iar ,

I created a simple LED blink program using modern C++ features and then performed the PR #17.

**Comment by felipe-iar** [comment]
Looks great, @sharpgeek .

Thank you for your contribution.

**Comment by sharpgeek** [comment]
Great! Thank you.
I will come up with more contributions soon.
